config/routes.rb
Rails.application.routes.draw do
    resources :products
    resources :sending_mailer

    root 'products#index'
    
    get 'send_mail' => 'products#send_mail'
    get 'download_pdf' => 'products#download_pdf'

end

app/models/product.rb
class Product < ActiveRecord::Base
	before_save :total
	def total
		self.totol_price = self.price + self.vat.to_i
		product = 1001 + Product.all.to_a.length
		self.product_id = 'PDCT-' + product.to_s
	end	
	has_attached_file :image, styles: { medium: "300x300>", large: "600x600>", thumb: "100x100#" }
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/	
	validates :title, :presence => 'true'
  	validates :price, :presence => 'true' , :numericality => {:only_integer => true}					
  	validates :quantity, :presence => 'true'
  	validates :vat, :presence => 'true'
  	validates :description, :presence => 'true'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_action :set_product, only: [:show, :edit, :update, :destroy]

	def index
		@products = Product.all.page(params[:page]).per(3)
		respond_to do |format|
		    format.html
		    format.xlsx do
				response.headers['Content-Disposition'] = 'attachment; filename="all_products.xlsx"'
				# render xlsx: 'products', template: 'my/template', filename: "my_products.xlsx", disposition: 'inline', xlsx_created_at: 3.days.ago, xlsx_author: "Rk"
			end
		end
	end

	def show
		
	end

	def new
		@product = Product.new
	end

	def edit
		
	end

	def send_mail
		@product = Product.all
		SendingMailer.new_mail(@product).deliver_now		
	end

	def download_pdf
		html = render_to_string(template: 'products/download_pdf.pdf.erb')
		pdf = PDFKit.new(html)
		send_data pdf.to_pdf, filename: "datareport.pdf", type: "application/pdf", disposition: "inline"
	end
	
	def create
		@product = Product.new(product_params)

		respond_to do |prdct|
			if @product.save
				prdct.html{ redirect_to @product, notice: 'product was successfully created' }
				prdct.json{ render :show, status: :created, location: @product }
			else
				prdct.html{ render :new }
				prdct.json{ render json: @product.errors, status: :unprocessible_entity }
			end
		end
	end

	def update
	    respond_to do |prdct|
	      if @product.update(product_params)
	        prdct.html { redirect_to @product, notice: 'Product was successfully updated.' }
	        prdct.json { render :show, status: :ok, location: @product }
	      else
	        prdct.html { render :edit }
	        prdct.json { render json: @product.errors, status: :unprocessable_entity }
	      end
	    end
  	end

  	def destroy
	    @product.destroy
	    respond_to do |prdct|
	      prdct.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
	      prdct.json { head :no_content }
	    end
  	end

  	private
    def set_product
      @product = Product.find(params[:id])
      @product = Product.all
	  SendingMailer.new_mail(@product).deliver_now
    end

    def product_params
      params.require(:product).permit( :product_id, :title, :price, :quantity, :vat, :totol_price, :description, :image)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProductApp</title>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name = "viewport" content = "width = device-width, initial-scale = 1.0">
</head>
<body>
<div class = "container">
	<%= yield %>
</div>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => "form-horizontal product", multipart: true  } do |f| %>

    <% if @product.errors.any? %>
      <div id="error_expl" class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h3>
        </div>
        <div class="panel-body">
          <ul>
          <% @product.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      </div>
    <% end %>
<div class = "container">
    <div class="form-group">
      <%= f.label :title, :class => 'control-label col-sm-4' %>
      <div class="col-sm-4">
        <%= f.text_field :title, :class => 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :price, :class => 'control-label col-sm-4' %>
      <div class="col-sm-4">
        <%= f.text_field :price, :class => 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :quantity, :class => 'control-label col-sm-4' %>
      <div class="col-sm-4">
        <%= f.text_field :quantity, :class => 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :vat, :class => 'control-label col-sm-4' %>
      <div class="col-sm-4">
        <%= f.text_field :vat, :class => 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :description, :class => 'control-label col-sm-4' %>
      <div class="col-sm-4">
        <%= f.text_field :description, :class => 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :image, :class => 'control-label col-sm-4' %>
      <div class="col-sm-4">
        <%= f.file_field :image %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-4 col-sm-4">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  products_path, :class => 'btn btn-default' %>
      </div>
    </div>

  </div>  
<% end %>

app/views/products/download_pdf.pdf.erb
<!--  <h2 class = "center">COMMERCIAL INVOICE</h2>
<table id = "border" style="width:100%">
<tr>
	<td colspan = '2'>Exporter<br>DEVI FISHERIES LIMITED,<br>6-21-7, EAST POINT COLONY,<br>VISAKHAPATNAM 530017, INDIA.<br><br>IMPORTER OF RECORD<br>DEVI FISHERIES LIMITED,<br>6-21-7, EAST POINT COLONY,<br>VISAKHAPATNAM 530017,INDIA.<br>IRS NO. 044601-01124</td><td class = "b_r"></td>
	<td>
		<table>
			<tr>
				<td class = "b_b b_r">Invoice No.<br>Date</td> <td class = "b_b">DFL/SAT/1617/076<br>08.07.2016</td>
			</tr>
			<tr>
				<td class = "b_b b_r">Purchase Order No.<br>Date</td> <td class = "b_b">139050<br>17.06.2016</td>
			</tr>
			<tr>
				<td class = "b_b" colspan = "2">Other Reference(s) :</td><td class = "b_b"><td>
			</tr>
			<tr>
				<td>MANUFACTURER / PACKER'S NAME AND ADDRESS :<br>SATYA SEA FOODS PVT, LTD.,<br>2-159, PANASAPADU, APSP CAMP.<br>KAKINADA 533 005, INDIA<br>BIO TERRORISM / USFDA REGISTRATION NO. 14848863246</td>
			</tr>
		</table>
	</td>
</tr>
<tr>
	<td colspan = "2" class = "b_t">Consignee<br>CHICKEN OF THE SEA FROZEN FOODS,<br>222 N. SEPULVEDA BLVD,<br>SUITE 1550, EL SEGUNDO,<br>CA 90245, U.S.A.</td><td class = "b_t b_r"></td>
	<td colspan = "2" class = "b_t">Notify Party :<br>WILLIAMS CLARKE CO., INC,<br>603, N.FRIES AVE., WILMINGTON,<br>CA 90744, U.S.A.</td>
	<td class = "b_t"></td>

</tr>
<tr>
	<td class = "b_t b_r" colspan = '2'>
		<table>
			<tr>
				<td class = "b_r">Pre-Carriage by<br></td>
				<td>Place of Receipt by Pre-carrier<br></td>
			</tr>	
		</table>	
	</td>
	<td></td>
	<td class = "b_t" colspan = '2'>
		<table>
			<tr>
				<td>Country of Origin of Goods<br>INDIA</td>
				
			</tr>	
		</table>	
	</td>
	<td></td>
</tr>
<tr>
	<td colspan = "2" class = "b_t b_r">
		<table>
			<tr>
				<td class = "b_r">Vessel/Flight No.</td>
				<td>Port of Loading<br>VISAKHAPATNAM</td>
			</tr>
			<tr>
				<td class = "b_t b_r">Vessel/Flight No.</td>
				<td class = "b_t">Port of Loading.</td>
			</tr>
		</table>
	</td>
	<td></td>
	<td colspan = "2" class = "b_t">
		<table>
			<tr rowspan = "2">
				<td colspan = "2">Terms of Delivery and payment<br>BY TT AFETR FDA</td>
			</tr>
		</table>
	</td>
</tr>	
<tr>
	<td class = "b_t" colspan = "3">Container No.  Kind of Pkgs.</td>
	<! <td class = "b_t">No. & Kind of Pkgs.</td> -->
	<!-- <td class = "b_t">Description of Goods</td> -->
	<!-- <td class = "b_t">
		<table>
			<tr>
				<td class = "b_r">Quantity</td>
				<td>Rate per LB</td>
			</tr>
		</table>
	</td>
</tr>	
</table> -->



<h2 class = "center">COMMERCIAL INVOICE</h2>
<table id = "border" style="width:100%">
	<tr>
		<td colspan = "4" class = "b_r">
			<p>Exporter</br><b>DEVI FISHERIES LIMITED</b>,<br><b>6-21-7, EAST POINT COLONY</b>,<br><b>VISAKHAPATNAM 530017, INDIA</b>.</p>
			<p>IMPORTER OF RECORD</br><b>DEVI FISHERIES LIMITED</b>,</br><b>6-21-7, EAST POINT COLONY</b>,</br><b>VISAKHAPATNAM 530017, INDIA.</b></br><b>IRS NO. 044601-01124</b></p>
		</td>
		<td colspan = "4">
			<table>
				<tr>
					<td><p>Invoice No.<br>Date</p></td>
					<td colspan = "3" class ="b_l"><p><b>DFL/SAT/1617/076</b><br><b>08.07.2016</b></p></td>
				</tr>
				<tr>
					<td><p>Purchase Order No.<br>Date</p></td>
					<td colspan = "3" class ="b_t b_l"><p><b>139050<br>08.07.2016</b></p></td>
				</tr>
				<tr><td colspan = "4" class ="b_t b_b">Other Reference(s) :</td></tr>
				<tr>
					<td colspan = "4">
						<p><b><u>MANUFACTURER / PACKER'S NAME AND ADDRESS :<br>SATYA SEA FOODS PVT, LTD.,<br>2-159, PANASAPADU, APSP CAMP.<br>KAKINADA 533 005, INDIA<br>BIO TERRORISM / USFDA REGISTRATION NO. 14848863246</u></b></p>
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td colspan = "4" class="b_t b_r b_b"><p>Consignee<br><b>CHICKEN OF THE SEA FROZEN FOODS,<br>222 N. SEPULVEDA BLVD,<br>SUITE 1550, EL SEGUNDO,<br>CA 90245, U.S.A.</b></p></td>
		<td colspan = "4" class="b_t  b_b"><p>Notify Party :<br><b>WILLIAMS CLARKE CO., INC,<br>603, N.FRIES AVE., WILMINGTON,<br>CA 90744, U.S.A.</b></p></td>
	</tr>
	<tr>
		<td colspan = "2">Pre-Carriage by<br></td>
		<td colspan = "2" class = "b_r">Place of Receipt by Pre-carrier<br></td>
		<td colspan = "2" class = "b_r"><p>Country of Origin of Goods</td>
		<td colspan = "3"><p>Country of Final Destination</td>
	</tr>
	<tr>
		<td colspan = "4" class ="b_b b_r" ></td>
		<td class = "center b_b b_r" colspan = "2"><b>INDIA</b></td>
		<td class = "center b_b" colspan = "2"><b>U.S.A</b></td>
	</tr>
	<tr>
		<td colspan = "2" class ="b_r">Vessel/Flight No.</td>
		<td colspan = "2" class ="b_r">Port of Loading</td>
		<td colspan = "4">Terms of Delivery and payment</td>
	</tr>
	<tr>
		<td colspan = "2" class = "b_b b_r">MV. LESOTHO V - 1613</td>
		<td class = "center b_b b_r" colspan = "2"><b>VISAKHAPATNAM</b></td>
		<td colspan = "4"><b>BY TT AFETR FDA</b></td>
	</tr>
	<tr>
		<td colspan = "2" class ="b_r">Port of Discharge</td>
		<td colspan = "2" class ="b_r">Final Place of Delivery <b>DDP</b></td>
		<td colspan = "4"></td>
	</tr>
	<tr>
		<td class = "center b_b b_r" colspan = "2"><b>LOS ANGELES, U.S.A.</b></td>
		<td class = "center b_b b_r" colspan = "2"><b>LOS ANGELES, U.S.A.</b></td>
		<td colspan = "4" class ="b_b"></td>
	</tr>
	<tr>
		<td class = "center b_b b_r">Marks & No's Container No.</td>
		<td class = "center b_b b_r">No. & Kind of Pkgs.</td>
		<td class = "center b_b b_r" colspan = "3">Description of Goods</td>
		<td class = "center b_r">Quantity</td>
		<td class = "center">Rate per LB</td>
		<td class = "center b_l">Amount US$</td>
	</tr>
	<tr>
		<td class = "center" colspan = "2"><b>3500 M/CS</b></td>
		<td class = "center b_r" colspan = "3"><b><u>CONTAINER NO. MWMU 6422966 SEAL NO. ML-IN 0609877</u></b></td>
		<td class = "center b_r"></td>
		<td class = "center"></td>
		<td class = "b_l"></td>
	</tr>
	<tr>
		<td colspan = "5" class = "b_r"><b><u>FROZEN RAW VANNAMEI WHITE PEELED AND DEVEINED TAIL ON IQF SHRIMPS PACKING : 4 X 2.5 LBS BRAND: PORTICO BOUNTY</u></b></td>
		<td class = "b_r"></td>
		<td></td>
		<td class = "b_l"><b><u>DDP PORT DELIVERY BASIS LOS ANGELES, U.S.A.</u></b></td>
	</tr>
	<tr>
		<td colspan = "2"></td>
		<td class = "center"><b><u>SIZE</u></b></td>
		<td colspan = "2" class = "center b_r"><b><u>NO.OF CTNS</u></b></td>
		<td class = "center b_r"><b><u>IN LBS.</u></b></td>
		<td class = "center"><b><u>IN US$</u></b></td>
		<td class = "b_l"></td>
	</tr>
	<tr>
		<td colspan = "2"></td>
		<td class = "center"><b>21/25</b></td>
		<td colspan = "2" class = "center b_r"><b>2700</b></td>
		<td class = "right b_r"><b>27000.000</u></b></td>
		<td class = "center"><b>4.95</b></td>
		<td class = "right b_l"><b>133650.00</b></td>
	</tr>
	<tr>
		<td colspan = "2"></td>
		<td class = "center"><b><u>TOTAL</u></b></td>
		<td colspan = "2" class = "center b_b b_t b_r"><b>2700</b></td>
		<td class = "right b_t b_r b_b"><b>27000.000</u></b></td>
		<td class = "center"></td>
		<td class = "right b_t b_b b_l"><b>133650.00</b></td>
	</tr>
	<tr>
		<td colspan = "4"><b><u>FROZEN RAW VANNAMEI WHITE PEELED AND DEVEINED TAIL ON IQF SHRIMPS PACKING : 5 X 2 LBS BRAND: COS</u></b></td>
		<td class = "b_r"></td>
		<td class = "b_r"></td>
		<td></td>
		<td class = "b_l"></td>
	</tr>
	<tr>
		<td colspan = "2"></td>
		<td class = "center"><b>21/25</b></td>
		<td colspan = "2" class = "center b_r"><b>800</b></td>
		<td class = "right b_r"><b>8000.000</b></td>
		<td class = "center"><b>4.95</b></td>
		<td class = "right b_l"><b>39600.00</b></td>
	</tr>
	<tr>
		<td colspan = "2"></td>
		<td class = "center"><b><u>TOTAL</u></b></td>
		<td colspan = "2" class = "center b_t b_r"><b>800</b></td>
		<td class = "right b_t b_r"><b>8000.000</b></td>
		<td></td>
		<td class = "right b_t b_l"><b>39600.00</b></td>
	</tr>
	<tr>
		<td colspan = "2"></td>
		<td class = "center"><b><u>GRAND TOTAL</u></b></td>
		<td colspan = "2" class = "center b_t b_b b_r"><b>3500</b></td>
		<td class = "right b_t b_b b_r"><b>35000.000</b></td>
		<td></td>
		<td class = "right b_t b_b b_l"><b>173250.00</b></td>
	</tr>
	<tr>
		<td colspan = "3"></td>
		<td><b>US$</b></td>
		<td class = "b_r"><b>US$</b></td>
		<td class = "b_r"></td>
		<td></td>
		<td class = "b_l"></td>
	</tr>
	<tr>
		<td colspan = "3" class = "center">INVOICE VALUE</td>
		<td colspan = "2" class = "right b_r">173250.00</td>
		<td colspan = "3"><b>GROSS WEIGHT : 45132.159 LBS</b></td>
	</tr>
	<tr>
		<td colspan = "3" class = "center">LESS : FREIGHT</td>
		<td colspan = "2" class = "right b_r">1800.00</td>
		<td colspan = "3"><b>NET WEIGHT : 35000.000 LBS.</b></td>
	</tr>
	<tr>
		<td colspan = "3"><b>(LESS : MERCHANDISE PROCESS FEE @ 0.3464 %)</b></td>
		<td colspan = "2" class = "b_b b_r right">485.00</td>
		<td colspan = "3"></td>
	</tr>
	<tr>
		<td colspan = "4"></td>
		<td class= "right b_r">170965.00</td>
		<td class= "b_r"></td>
		<td></td>
		<td class = "b_l"></td>
	</tr>
	<tr>
		<td></td>
		<td colspan = "2"><b>(US$. 170965.00 X 3.4050/ 103.4050)</b></td>
		<td colspan = "2" class = "right b_r">5629.67</td>
		<td class= "b_r"></td>
		<td></td>
		<td class = "b_l"></td>
	</tr>
	<tr>
		<td></td>
		<td colspan = "2"><b>FOB VALUE</b></td>
		<td colspan = "2" class = "right b_t b_r b_b">165335.33</td>
		<td class= "b_r"></td>
		<td></td>
		<td class = "b_l"></td>
	</tr>
	<tr>
		<td colspan = "6" class = "b_t">Amount Chargeable</td>
		<td class = "b_t">Total</td>
		<td class = "right b_t b_l b_b"><b>173250.00</b></td>
	</tr>
	<tr>
		<td colspan = "6"><b>(in words) ( US DOLLARS ONE HUNDRED SEVENTY THREE THOUSAND TWO HUNDRED AND FIFTY ONLY)</b></td>
		<td colspan = "2"></td>
	</tr>
	<tr>
		<td colspan = "8">EACH M/CTNS. CONSISTS OF NET WT. 10.0 LBS . AND GROSS WT. 12.89 LBS.</td>
	</tr>
	<tr>
		<td colspan = "6"></td>
		<td colspan = "2"  class = "b_t b_l">for DEVI FISHERIES LIMITED</td>
	</tr>
	<tr></tr>
	<tr>
		<td colspan = "6">Declaration:</td>
		<td colspan = "2"  class = "b_l"></td>
	</tr>
	<tr>
		<td colspan = "5">We declare that this invoice shows the actual price of the goods described and that all particulars are true and correct</td>
		<td></td>
		<td colspan = "2" class = "b_l">AUTHORISED SIGNATORY Signature & Date</td>
	</tr>
</table>

 
<style type="text/css">
/*table, th, td {
    border:  solid 1px black;
    
    border-collapse: none;
}*/
td{
	font-size: 12px;
}
.top_space{
	padding-top: -150px;
}
.right{
	text-align: right;
}
.center{
	text-align: center;
}
#border{
	border: 1px solid black;
}
.b_t{
	border-top: 1px solid black;
}
.b_r{
	border-right: 1px solid black;
}
.b_b{
	border-bottom: 1px solid black;
}
.b_l{
	border-left: 1px solid black;
}
.b_l .b_t .b_r .b_b .border{
	border-collapse: collapse;
}
</style>

app/views/products/edit.html.erb
<div class="page-header">
  <h1>Edit Product</h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<div class="page-header">
  <h1>Products</h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= check_box_tag 'tick' %> <strong>Show all</strong></th>
      <th>id</th>
      <th>Product id</th>
      <th>Title</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Vat</th>
      <th>Total price</th>
      <th>Image</th>
      <th>Description</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= check_box_tag 'row_check' %></td>
        <td><%= product.id %></td>
        <td><%= product.product_id %></td>
        <td><%= product.title %></td>
        <td><%= product.price %></td>
        <td><%= product.quantity %></td>
        <td><%= product.vat %></td>
        <td><%= product.totol_price %></td>
        <td><%= image_tag product.image.url(:thumb) %></td>
        <td><%= product.description %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_path(product), :class => 'btn btn-default btn-xs' %>
          
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<table class = 'table'>
  <tr>
    <td class = "col-sm-5"><%= link_to t('.new', :default => t("helpers.links.new")), new_product_path, :class => 'btn btn-primary' %></td>
    <td class = "col-sm-offset-4 col-sm-7"><%= paginate @products %></td>
    <td class = "col-sm-4">
          <%= link_to 'send mail', send_mail_path, :class => 'btn btn-primary sending' %>
    </td>
  </tr>
  <tr>
    <%= link_to 'Download as excel', products_path(format: :xlsx) %><br>
    <%= link_to 'Download Pdf Report', download_pdf_path(format: 'pdf') %>
  </tr>
</table>

<script type="text/javascript">
$(document).ready(function () {
    $('.sending').click(function(){
      var href = $('.sending').attr('href')
      href = href + "?id =52}'"
      $('.sending').attr("href",href)
    });


    var ckbox = $('#tick');
    $('input').on('click',function () {
        if (ckbox.is(':checked')) {
            alert('You have Checked it');
        } else {
            alert('You Un-Checked it');
        }
    });
});

</script>

app/views/products/new.html.erb
<div class="page-header">
  <h1>New Product</h1>
</div>
<%= render :partial => 'form' %>

app/views/products/send_mail.html.erb
<h3 style = "color:green">sending successfull</h3>

<%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn btn-sm btn-primary'  %>

app/views/products/show.html.erb
<div class="page-header">
  <h1>Product</h1>
</div>
<%= image_tag @product.image.url(:medium) %>
<dl class="dl-horizontal">
  <dt><strong>Product id:</strong></dt>
  <dd><%= @product.product_id %></dd>
  <dt><strong>Title:</strong></dt>
  <dd><%= @product.title %></dd>
  <dt><strong>Price:</strong></dt>
  <dd><%= @product.price %></dd>
  <dt><strong>Quantity:</strong></dt>
  <dd><%= @product.quantity %></dd>
  <dt><strong>Vat:</strong></dt>
  <dd><%= @product.vat %></dd>
  <dt><strong>Total price:</strong></dt>
  <dd><%= @product.totol_price %></dd>
  <dt><strong>Description:</strong></dt>
  <dd><%= @product.description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>